# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://dpg-d8tsosm7r5hc73ampip0-a.singapore-postgres.render.com/moneymanager_3oax
spring.datasource.username=${POSTGRE_NAME}
spring.datasource.password=${POSTGRE_PASS}

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Override the MySQL dialect from base config
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect