spring.application.name=moneymanager

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/moneymanager?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.format-sql=true          # fixed typo (no underscores)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server
server.servlet.context-path=/api/v1.0
server.port=8080

# Email (Brevo)
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=$(MAIL_USERNAME)
spring.mail.password=$(MAIL_PASS)  

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.from=sujitgavali451@gmail.com
#jwt
jwt.secret=${JWT_TOKEN}
jwt.expiration=86400000



money.manager.frontend.url=http://localhost:5173


app.activation.url=http://localhost:8080
spring.profiles.active=prod