# PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d8tsosm7r5hc73...
spring.datasource.username=${POSTGRE_NAME}
spring.datasource.password=${POSTGRE_PASS}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Brevo HTTP API
brevo.api.key=${BREVO_API_KEY}
spring.mail.from=${MAIL_MAIL}